### PR TITLE
#60: Test cases for OAuth2PlatformClient

### PR DESCRIPTION
**Pull request by bhavinshah7**

### CODE REVIEW

**Comment by bhavinshah7** [comment]
@diana-derose Could you please review my PR? I am not sure why it is failing for jdk9 and above.

**Comment by diana-derose** [comment]
@scanbns - Could you add the following code above the jacoco plugin in [pom.xml](https://github.com/intuit/QuickBooks-V3-Java-SDK/blob/develop/oauth2-platform-api/pom.xml)`			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M3</version>
				<configuration>
					<argLine>${argLine} -Djdk.attach.allowAttachSelf</argLine>
				</configuration>
			</plugin>`

**Comment by bhavinshah7** [comment]
@diana-derose Thanks for the quick response. it worked.

**Review by diana-derose — APPROVED** [review]

**Comment by diana-derose** [comment]
Awesome thanks!

**Pull request merged**
