### PR TITLE
Propagate fault even there is no responses (#75) 

### LINKED ISSUE #75: Fault with error is getting eaten if response is null
Need to clarify behaviour of [getCDCQueryResult(CDCResponse cdcResponse)](https://github.com/intuit/QuickBooks-V3-Java-SDK/blob/develop/ipp-v3-java-devkit/src/main/java/com/intuit/ipp/interceptors/CallbackHandlerInterceptor.java#L243-L245).

Current implementation expects to populate CDCResult with **fault** object (`else-if` branch) if no responses available.
But this never happens because  [getQueryResponse()](https://github.com/intuit/QuickBooks-V3-Java-SDK/blob/develop/ipp-v3-java-data/src/main/java/com/intuit/ipp/data/CDCResponse.java#L92-L97) lazily initializes list internally, therefore expression `queryResponses != null` never resolves to `false`.

PS
And there is a type in `falut` on CDC query response object.

```java
List<QueryResponse> queryResponses = cdcResponse.getQueryResponse();
if (queryResponses != null) {
	//....
} else if (cdcResponse.getFault() != null) {
	cdcQueryResult.setFalut(cdcResponse.getFault());
}
```
 **errorNoResponse** test in  [CallbackHandlerInterceptorCDCTest](https://github.com/intuit/QuickBooks-V3-Java-SDK/pull/74/files#r337231044) demonstrates details of this issue.

@diana-derose would you mind to share your expertise and specify expected behavior?

### PR DESCRIPTION
**Pull request by amatiushkin**
Fixes #75

### CODE REVIEW

**Comment by amatiushkin** [comment]
Coverage should be better with #74 :)

**Review by diana-derose — APPROVED** [review]

**Comment by diana-derose** [comment]
Alex - This looks good, the PR is still in draft so can't merge. Let me know once complete and I'll merge this along with #74

**Comment by amatiushkin** [comment]
@diana-derose let's take #74 first, I do expect one  new test to fail and to be re-implemented in scope of this PR.

**Comment by amatiushkin** [comment]
@diana-derose it is ready :)

**Review by diana-derose — APPROVED** [review]

**Comment by diana-derose** [comment]
Looks good, thanks @amatiushkin

**Pull request merged**
