### PR TITLE
 intuit#128 : updated IntuitBatchInterceptorProvider.java to throw FMSException with intuit_tid

### PR DESCRIPTION
**Pull request by praveenadg**

### CODE REVIEW

**Review by Emilyhbx01 — APPROVED** [review]
Thanks! That's what I need. There's a spelling mistake in 'httpresponse'.

**Review by mahajanpr — APPROVED** [review]
looks good

**Comment by Emilyhbx01** [comment]
@praveenadg could you provide me with the updated jar file pls? Thank you!

**Comment by Emilyhbx01** [comment]
@praveenadg hello, how can I download the updated jar files because the jar files at QuickBooks API documentation hasn't been updated?

**Pull request merged**
