### PR TITLE
#hacktoberfest SerializeInterceptor - Unit Tests Coverage and Bug Fix

### PR DESCRIPTION
**Pull request by cho8**
Issue #60 -- Increased Code Coverage.
Fixed a bug where file mime returned always included delimiter. 
Refactored and added unit tests.

### CODE REVIEW

**Comment by cho8** [comment]
@diana-derose Can I get some feedback on this PR?

**Comment by diana-derose** [comment]
@cho8  - Could you explain what was the bug in the getMime method?

**Comment by cho8** [comment]
@diana-derose The `getMime` method was returning the delimiter when it parses for the file mime.

The `beginIndex` in `substring(int beginIndex, int endIndex)` is inclusive. In the case of `getMime`, this means it will include the delimiter when it parses out the mime on line 205:
`return name.substring(name.lastIndexOf(delimiter), name.length());`

e.g. `filename.jpg` would result in `.jpg` instead of just `jpg`

If the file uploaded is an image, the image content would never be retrieved as intended since the returned mime would never match a known image type from line 49
`private static final String[] IMAGE_MIMES = {"jpg", "jpeg", "tif", "tiff", "gif", "png", "bmp"};` 

This PR fixes this issue by incrementing the beginIndex by 1
`return name.substring(name.lastIndexOf(delimiter) + 1, name.length());`

**Comment by cho8** [comment]
The above is also true for when `getMime` is used to check content-type
e.g.  `'image/jpg` would have returned as `/jpg`

**Review by diana-derose — APPROVED** [review]

**Comment by diana-derose** [comment]
@cho8 - Thanks for the details, I have approved it.

**Pull request merged**
